### ISSUE TITLE
X-API-Key people selector needs to be searchable

### ISSUE THREAD

**Issue by stakach** [PlaceOS/backoffice#241] opened 2021-09-28 04:47 UTC
Not all results are returned and there is no way to filter for the desirable user, making selection difficult

![image](https://user-images.githubusercontent.com/368013/135024902-c4b9e154-e439-4ca9-9e2d-d768861e59ee.png)

**Comment by MrYuion** [comment] 2021-09-28 05:04
This is a duplicate of #229

**Closed as completed by MrYuion** 2021-09-28 05:04 UTC
Labels: front end, focus: front end, type: bug
