### ISSUE TITLE
Adding a module of type Driver fails with `A valid URI is required`

### ISSUE THREAD

**Issue by PhilPearson** [PlaceOS/backoffice#68] opened 2020-06-18 05:31 UTC
**Describe the bug**
Unable to add a new module to a system due to backoffice now requiring a URI for device type drivers.

`A valid URI is required`

**To Reproduce**
Add a driver, type 'device'
Add a module to a system, using this driver

**Expected behavior**
Enter IP and click save, works.
URI should not be required for `device` type driver modules.

**Additional context**

**Comment by alexchuvand** [comment] 2020-06-23 05:34
Fixed with Duplicate of #72

**Closed by alexchuvand** 2020-06-23 05:34 UTC
Labels: bug
